apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-admission-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-admission-controller
  template:
    metadata:
      labels:
        app: vpa-admission-controller
    spec:
      containers:
      - name: vpa-admission-controller
        image: gcr.io/k8s-staging-autoscaling/vpa-admission-controller:v0.8.0
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: vpa-admission-controller
  namespace: kube-system
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: vpa-admission-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-controller
  template:
    metadata:
      labels:
        app: vpa-controller
    spec:
      containers:
      - name: vpa-controller
        image: gcr.io/k8s-staging-autoscaling/vpa-recommender:v0.8.0
