apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: my-namespace
spec:
  containers:
  - name: my-container
    image: nginx
    env:
    - name: CONFIG_KEY1
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: key1
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
