apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DATABASE_HOST: mysql
  DATABASE_PORT: "3306"
  DATABASE_NAME: mydatabase
  DATABASE_USER: root
  DATABASE_PASSWORD: rootpassword
